version: 2

project_name: deel

before:
  hooks:
    - go mod tidy

builds:
  # Darwin build with CGO enabled for macOS keychain access
  - id: darwin
    main: ./cmd/deel
    binary: deel
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/salmonumbrella/deel-cli/internal/cmd.Version={{.Version}}
      - -X github.com/salmonumbrella/deel-cli/internal/cmd.Commit={{.Commit}}
      - -X github.com/salmonumbrella/deel-cli/internal/cmd.BuildDate={{.Date}}

  # Linux and Windows builds without CGO
  - id: other
    main: ./cmd/deel
    binary: deel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/salmonumbrella/deel-cli/internal/cmd.Version={{.Version}}
      - -X github.com/salmonumbrella/deel-cli/internal/cmd.Commit={{.Commit}}
      - -X github.com/salmonumbrella/deel-cli/internal/cmd.BuildDate={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: salmonumbrella
    name: deel-cli
  draft: false
  prerelease: auto

